# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=17)),
                ('username', models.CharField(max_length=17)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='profiles',
            field=models.ManyToManyField(to='recommend.Profile'),
        ),
    ]
