# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20170327_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='played_games',
            field=models.ManyToManyField(related_name='played_games', to='recommend.Game'),
        ),
    ]
