# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_remove_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=-1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_games',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owned_games',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='played_games',
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(related_name='owned_games', to='recommend.Game_Entry'),
        ),
    ]
